import os


PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

class Config:
    """
    Configuration class for the entire project.
    """

    def __init__(self):
        # =================================================================
        # Data & Feature Parameters
        # =================================================================
        # TODO: Update this path to your Qlib data directory.
        self.qlib_data_path = "~/.qlib/qlib_data/cn_data"
        self.instrument = 'csi300'

        # Overall time range for data loading from Qlib.
        self.dataset_begin_time = "2011-01-01"
        # Dataset now covers full history through 2026-08-06 (140 symbols).
        self.dataset_end_time = '2026-08-06'

        # Sliding window parameters for creating samples.
        self.lookback_window = 128  # Number of past time steps for input.
        self.predict_window = 10  # Number of future time steps for prediction.
        self.max_context = 512  # Maximum context length for the model.

        # Features to be used from the raw data.
        self.feature_list = ['open', 'high', 'low', 'close', 'vol', 'amt']
        # Time-based features to be generated.
        self.time_feature_list = ['minute', 'hour', 'weekday', 'day', 'month']

        # =================================================================
        # Dataset Splitting & Paths
        # =================================================================
        # Note: The validation/test set starts earlier than the training/validation set ends
        # to account for the `lookback_window`.
        self.train_time_range = ["2011-01-01", "2022-12-31"]
        self.val_time_range = ["2022-09-01", "2024-06-30"]
        self.test_time_range = ["2024-04-01", "2026-08-06"]
        self.backtest_time_range = ["2024-07-01", "2026-08-06"]

        # Generated by data/build_local_finetune_dataset.py. The accompanying
        # manifest is checked by QlibDataset before any samples are used.
        self.dataset_path = os.getenv(
            "KRONOS_DATASET_PATH",
            os.path.join(PROJECT_ROOT, "data", "a_share_finetune_multiboard"),
        )

        # =================================================================
        # Training Hyperparameters
        # =================================================================
        self.clip = 5.0  # Clipping value for normalized data to prevent outliers.

        # The prior run started overfitting after its first epoch.  Keep the
        # default conservative and let early stopping select the checkpoint.
        self.epochs = int(os.getenv("KRONOS_FINETUNE_EPOCHS", "8"))
        self.log_interval = 100  # Log training status every N batches.
        self.batch_size = int(os.getenv("KRONOS_FINETUNE_BATCH_SIZE", "50"))  # Batch size per GPU.

        # Number of samples to draw for one "epoch" of training/validation.
        # This is useful for large datasets where a true epoch is too long.
        self.n_train_iter = int(os.getenv("KRONOS_FINETUNE_TRAIN_SAMPLES", str(2000 * self.batch_size)))
        self.n_val_iter = int(os.getenv("KRONOS_FINETUNE_VAL_SAMPLES", str(400 * self.batch_size)))

        # Learning rates for different model components.
        self.tokenizer_learning_rate = 2e-4
        self.predictor_learning_rate = float(
            os.getenv("KRONOS_PREDICTOR_LR", "5e-6")
        )
        # Direct, actionable endpoints.  `predict_window` stays at ten so the
        # original token task and inference path do not train beyond two weeks.
        self.forecast_horizons = (1, 3, 5, 10)
        self.forecast_pool_size = int(os.getenv("KRONOS_FORECAST_POOL_SIZE", "16"))
        self.forecast_head_dropout = 0.1
        self.return_loss_weight = 1.0
        self.direction_loss_weight = float(
            os.getenv("KRONOS_DIRECTION_LOSS_WEIGHT", "0.25")
        )
        self.direction_min_deadzone = float(
            os.getenv("KRONOS_DIRECTION_MIN_DEADZONE", "0.003")
        )
        self.direction_volatility_multiplier = float(
            os.getenv("KRONOS_DIRECTION_VOL_MULT", "0.5")
        )
        self.return_huber_delta = 0.02
        # Sign-consistency loss between direction head and return head.
        # Penalises P(up)>P(down) but return<0 (or vice versa).  0 = disabled.
        self.consistency_loss_weight = float(
            os.getenv("KRONOS_CONSISTENCY_LOSS_WEIGHT", "0.0")
        )
        # Optional class weights for the 3-class direction loss (down/flat/up).
        # When provided (comma-separated, e.g. "1.5,0.4,1.5"), upweights
        # actionable UP/DOWN calls so the head does not collapse to FLAT.
        raw_cw = os.getenv("KRONOS_DIRECTION_CLASS_WEIGHTS", "")
        self.direction_class_weights = (
            [float(x) for x in raw_cw.split(",")] if raw_cw.strip() else None
        )
        # Direction loss type: "ce" (default) or "focal".
        # Focal loss: -alpha_t * (1-p_t)^gamma * log(p_t), focuses on hard
        # UP/DOWN examples that CE over-dilutes with easy FLAT majority.
        self.direction_loss_type = os.getenv("KRONOS_DIRECTION_LOSS_TYPE", "ce")
        self.focal_gamma = float(os.getenv("KRONOS_FOCAL_GAMMA", "2.0"))
        # Label smoothing for direction CE (0.0 = hard labels). Softens
        # overconfident UP/DOWN predictions, mild regularisation.
        self.direction_label_smoothing = float(
            os.getenv("KRONOS_DIR_LABEL_SMOOTHING", "0.0"))
        # UP-DOWN swap penalty: extra loss for P(opposite class) on true
        # UP/DOWN samples. Targets the worst error type (direction reversal).
        # 0.0 = disabled.
        self.swap_penalty_weight = float(
            os.getenv("KRONOS_SWAP_PENALTY_WEIGHT", "0.0"))

        # Controlled-experiment toggles (Phase-2 finetune optimisation).
        # When freeze_backbone is True the Kronos backbone parameters are
        # frozen and only the MultiHorizonForecastHead is trained; a higher
        # head learning rate is used because the head starts from random init.
        self.freeze_backbone = os.getenv("KRONOS_FREEZE_BACKBONE", "0") == "1"
        self.head_learning_rate = float(
            os.getenv("KRONOS_HEAD_LR", "5e-4")
        )
        # Optional experiment tag appended to the save folder so multiple
        # experiments do not overwrite each other.
        self.exp_name = os.getenv("KRONOS_EXP_NAME", "")
        self.early_stopping_patience = int(
            os.getenv("KRONOS_EARLY_STOPPING_PATIENCE", "2")
        )

        # Gradient accumulation to simulate a larger batch size.
        self.accumulation_steps = 1

        # AdamW optimizer parameters.
        self.adam_beta1 = 0.9
        self.adam_beta2 = 0.95
        self.adam_weight_decay = 0.1

        # Miscellaneous
        self.seed = 100  # Global random seed for reproducibility.

        # =================================================================
        # Experiment Logging & Saving
        # =================================================================
        self.use_comet = False # Set to True only after configuring Comet ML
        self.comet_config = {
            # It is highly recommended to load secrets from environment variables
            # for security purposes. Example: os.getenv("COMET_API_KEY")
            "api_key": "YOUR_COMET_API_KEY",
            "project_name": "Kronos-Finetune-Demo",
            "workspace": "your_comet_workspace" # TODO: Change to your Comet ML workspace name
        }
        self.comet_tag = 'finetune_demo'
        self.comet_name = 'finetune_demo'

        # Base directory for saving model checkpoints and results.
        # Using a general 'outputs' directory is a common practice.
        self.save_path = os.path.join(PROJECT_ROOT, "outputs", "models")
        self.tokenizer_save_folder_name = 'a_share_multi_tokenizer'
        base_predictor_name = 'a_share_multihorizon_predictor'
        if self.exp_name:
            base_predictor_name = f"{base_predictor_name}_{self.exp_name}"
        self.predictor_save_folder_name = base_predictor_name
        self.backtest_save_folder_name = 'finetune_backtest_demo'

        # Path for backtesting results.
        self.backtest_result_path = "./outputs/backtest_results"

        # =================================================================
        # Model & Checkpoint Paths
        # =================================================================
        # TODO: Update these paths to your pretrained model locations.
        # These can be local paths or Hugging Face Hub model identifiers.
        self.pretrained_tokenizer_path = os.path.join(PROJECT_ROOT, "weights", "Kronos-Tokenizer-base")
        previous_predictor_path = os.path.join(
            PROJECT_ROOT,
            "outputs",
            "models",
            "a_share_multi_predictor",
            "checkpoints",
            "best_model",
        )
        self.pretrained_predictor_path = os.getenv(
            "KRONOS_INIT_PREDICTOR",
            previous_predictor_path if os.path.exists(previous_predictor_path)
            else os.path.join(PROJECT_ROOT, "weights", "Kronos-base"),
        )

        # Paths to the fine-tuned models, derived from the save_path.
        # These will be generated automatically during training.
        self.finetuned_tokenizer_path = f"{self.save_path}/{self.tokenizer_save_folder_name}/checkpoints/best_model"
        self.finetuned_predictor_path = f"{self.save_path}/{self.predictor_save_folder_name}/checkpoints/best_model"

        # =================================================================
        # Backtesting Parameters
        # =================================================================
        self.backtest_n_symbol_hold = 50  # Number of symbols to hold in the portfolio.
        self.backtest_n_symbol_drop = 5  # Number of symbols to drop from the pool.
        self.backtest_hold_thresh = 5  # Minimum holding period for a stock.
        self.inference_T = 0.6
        self.inference_top_p = 0.9
        self.inference_top_k = 0
        self.inference_sample_count = 5
        self.backtest_batch_size = 1000
        self.backtest_benchmark = self._set_benchmark(self.instrument)

    def _set_benchmark(self, instrument):
        dt_benchmark = {
            'csi800': "SH000906",
            'csi1000': "SH000852",
            'csi300': "SH000300",
        }
        if instrument in dt_benchmark:
            return dt_benchmark[instrument]
        else:
            raise ValueError(f"Benchmark not defined for instrument: {instrument}")
